### ISSUE TITLE
const confirm = useConfirm(); always returns undefined

### ISSUE THREAD

**Issue by gardengeek99** [jonatanklosko/material-ui-confirm#29] opened 2021-05-10 16:35 UTC
New to using hook functions, but I can't figure out why this always happens.

Ideas?

**Comment by gardengeek99** [comment] 2021-05-10 16:54
Yes, I am using MuiThemeProvider and originally had ConfirmProvider as a child.  However, I removed MuiThemeProvider ensuring ConfirmProvider was outermost and still the same issue.

**Comment by jonatanklosko** [comment] 2021-05-10 16:56
And I assume you are calling `useConfirm` in a functional component in that component tree? Seems weird, are there any significant differences between your usage and the demo?

**Comment by gardengeek99** [comment] 2021-05-10 18:00
I am.  I don't see anything very different from the samples.

**Comment by gardengeek99** [comment] 2021-05-10 18:01
I guess one somewhat significant difference is my app is typescript.

**Comment by KarolError404** [comment] 2021-05-13 14:22
Did you try to use useConfirm(...) in child component? I can see it happening when you're wrapping component in <ConfirmProvider> and use useConfirm(...) in the same component.

**Comment by magnusvk** [comment] 2021-05-26 19:33
@KarolError404 thanks for that pointer—this is what I was doing to run into this. Perhaps this could be more clear in the docs?

**Comment by jonatanklosko** [comment] 2021-05-26 19:44
That's generally the case for the context provider + hooks pattern, common in many packages. I added  a tiny clarification to the readme (043ccd458004a33fc48cd203868d376fc2c591de).

@gardengeek99 does this match your case?

**Comment by magnusvk** [comment] 2021-05-26 20:49
Yes that’s helpful for someone like me who is still new to React, thank you!

**Comment by atompie** [comment] 2021-06-15 10:39
Hi I ave the same issue: undefined confirm.

`import { useConfirm, ConfirmProvider } from 'material-ui-confirm';

export default function TagTextForm({label, placeholder, onChange}) {
    const classes = useStyles();
    const confirm = useConfirm();
    console.log(confirm)   //undefined
    const handleChange = (ev, value, reason) => {
        console.log("confirm", confirm) //undefined
    }

    return (
        <div className={classes.root}>
            <ConfirmProvider>
                <Autocomplete
                    multiple
                    id="tags-text"
                    onChange={(ev, value, reason) =>
                    ....
                />
            </ConfirmProvider>
        </div>
    );
}
`

What I am doing wrong?

**Comment by jonatanklosko** [comment] 2021-06-15 10:41
@atompie the `TagTextForm` component needs to itself be wrapped in `ConfirmProvider`. Generally you want to keep `ConfirmProvider` at the very top level in the `App` component, similarly to router, theme provider, etc.

**Comment by atompie** [comment] 2021-06-15 10:43
Ok I got it . I Wrapped Autocomplete in ConfirmProvider but it is too deep. Thanks. A great work with material-ui-confirm :)

**Comment by jonatanklosko** [comment] 2022-02-27 22:24
Since there is no reproduction, I'm going to close this for now.

**Closed by jonatanklosko** 2022-02-27 22:24 UTC

**Comment by sneko** [comment] 2023-01-11 14:02
I had this issue too:
* In my Next.js project it worked great
* In my Storybook wrapping my stories with the general decorator was not working with `ConfirmProvider` whereas all my other providers work great

My "workaround" is to set the decorator on the story instead of on all stories (inside `preview.jsx`). I can't explain why... hope this helps!

**Comment by jonatanklosko** [comment] 2023-01-11 23:13
Interesting, it does work for the stories in this repo:

https://github.com/jonatanklosko/material-ui-confirm/blob/4cb9a104eebbd8f490fd731fde27418fef8952ee/stories/index.stories.js#L210-L212
