### ISSUE TITLE
Neutrally closing the dialog (e.g. when hitting Esc) causes code to hang

### ISSUE THREAD

**Issue by aheimlich** [jonatanklosko/material-ui-confirm#25] opened 2021-03-18 00:58 UTC
Affected version: 2.1.1

When you close a confirm dialog neutrally (i.e. hit `ESC` or click the backdrop), it causes the code that invoked `confirm()` to hang.

You can see an example of this at https://codesandbox.io/s/material-ui-confirm-demo-forked-67mfw?file=/src/Demo.js. Opening the confirm dialog causes the current timestamp to be logged to the console at a regular interval. If you click either of the buttons, the console logging is stopped appropriately. If hit `ESC` or click the backdrop, the console logging still continues, even when the dialog closes. If you open the confirm dialog again, there are now two processes logging the current timestamp to the console.

**Comment by jonatanklosko** [comment] 2021-03-30 20:30
Hey @aheimlich, this is actually expected behaviour with `async/await`, because the underlying promise is neither resolved nor rejected (the natural closing pretends nothing have happened). See #17.

**Comment by joshkel** [comment] 2021-06-15 14:48
I wrapped material-ui-confirm to return a boolean; that seemed like a more convenient interface for `async/await`. Here's a TypeScript version that uses a Material-UI Dialog onExited handler to detect where the dialog is neutrally closed; it returns `true`, `false`, or `null` if the dialog is confirmed, canceled, or neutrally closed, respectively.

```
    async function useAwaitConfirm(options: Omit<ConfirmOptions, 'dialogProps'>): Promise<boolean | null> => {
      const exitPromise = { resolve: noop };
      const exited = new Promise<void>((resolve) => {
        exitPromise.resolve = resolve;
      });

      options.dialogProps = { open: false, onExited: () => exitPromise.resolve() };

      let confirmed: boolean | null = null;
      await Promise.race([
        exited,
        confirm(useOptions)
          .then(() => (confirmed = true))
          .catch(() => (confirmed = false)),
      ]);
      return confirmed;
  }
```

**Comment by Nonag** [comment] 2021-08-03 13:23
So what is your suggestion on handling the "disappearance" of a promise? Clearly this can be a major issue as @aheimlich example shows. Sometimes it can not be avoided to change the state or start certain processes before showing the dialog to the user. We now lack a reliable method to also "pretend that nothing happened" and revert the changes that were made in the try-block.

One could use the `onExited` callback in the `dialogProps` and treat is as the `finally` method. But that is kind of obfuscated.

My understanding of a "confirmation dialog" is, I can either accept or deny. Sneaking my way out by clicking the backdrop is also just the opposite of accepting.

Maybe a `rejectOnClose` option could be something to consider?

**Comment by Nonag** [comment] 2021-08-03 14:39
As a workaround I ended up wrapping the `confirm()` promise in another promise, rejecting it on the `dialogProps`\` `onBackdropClick` and `onEscapeKeyDown` callbacks.

For anyone who struggles with this:
```JavaScript
await new Promise((resolve, reject) =>
  confirm({
    dialogProps: {
      onBackdropClick: () => reject('denied'),
      onEscapeKeyDown: () => reject('denied'),
    },
  })
    .then(() => resolve('confirmed'))
    .catch(() => reject('denied')),
);
```

**Comment by aheimlich** [comment] 2021-08-03 19:39
For my current project, I plan on using @joshkel‘s solution at https://github.com/jonatanklosko/material-ui-confirm/issues/25#issuecomment-861564274

**Comment by jonatanklosko** [comment] 2022-02-27 23:04
I think the current behaviour makes the most sense with the promise API. The impression of "hanging" is the result of the promise never resolving, which is expected as of #17.

The alternative API resolving to a boolean is also fine, but in most cases the only relevant event is confirmation and this API would make it more cumbersome. It would also be more error prone, as the user may expect `then` callback to be invoked on confirmation (so they would _just need to remember_ to always check the boolean). In the end, I don't think it's worth it, especially that it's a breaking change.

**Closed by jonatanklosko** 2022-02-27 23:04 UTC
